### ISSUE TITLE
BigQuery Connector fail when loading empty partitions

### ISSUE THREAD

**Issue by nkijak** [GoogleCloudPlatform/bigdata-interop#100]
When trying to load a partition that happens to be empty, it appears that an empty file is created but has an index of 1 instead of 0. This leads to the following error to be thrown:
```
 java.lang.IllegalStateException: Found known file 'data-000000000001.json' with index 1, which isn't less than or equal to than endFileNumber 0!
	at com.google.cloud.hadoop.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at com.google.cloud.hadoop.io.bigquery.DynamicFileListRecordReader.setEndFileMarkerFile(DynamicFileListRecordReader.java:340)
	at com.google.cloud.hadoop.io.bigquery.DynamicFileListRecordReader.nextKeyValue(DynamicFileListRecordReader.java:190)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:207)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This is caused by what I think is the simplest way to get data (which loads fine when data exists)
```
BigQueryConfiguration.configureBigQueryInput(
      conf,
      projectId,
      dataset,
      tableName + "$" + DateTimeFormat.forPattern("YYYYMMdd").print(forDate))
    spark.sparkContext
      .newAPIHadoopRDD(conf,
                       classOf[GsonBigQueryInputFormat],
                       classOf[LongWritable],
                       classOf[JsonObject])
      .map(unmarshaller.unmarshall)
```

**Comment by pmkc** [comment]
You can try getting around that by disabling the (now deprecated) sharded output with:
conf.set("mapred.bq.input.sharded.export.enable", "false")

That being said the error above should never happen unless BigQuery had a fluke error you are reusing the staging directory for import (which did not happen) in my testing. 

Are you trying to read a range of date partitions in parallel and join them in the same RDD?

**Comment by nkijak** [comment]
Not dates in parallel at the moment, but I am reading from two different tables.  Are you saying that the extract would be writing the temp files to the same location?  One table having data, producing files and the second not having any records and, in looking in the same location and seeing files, throwing this error?

**Comment by pmkc** [comment]
The connector uses the MapReduce JobId as a unique identifier for the temorary, which I was concerned was not unique between RDDs, though it is.

I didn't repro this in Spark (even when reading from an empty partition), but  now I'm seeing the two empty JSON files for `bq extract --destination_format NEWLINE_DELIMITED_JSON 'table$20180531' 'gs://.../*.json'`, which would cause this. I don't believe that is supposed to happen on BigQuery's end.

In the meantime I would strongly suggest disabling sharded exports with `conf.set("mapred.bq.input.sharded.export.enable", "false")`. It has been deprecated anyways.

**Comment by pmkc** [comment]
Because sharded export is disabled by default (in the next connector version) and this only affects empty date partitions. I don't think we are going to fix this on our end.
