### ISSUE TITLE
Unable to use Dataproc cluster for multi user with GCS with restricted access to user

### ISSUE THREAD

**Issue by krishnabigdata** [GoogleCloudPlatform/bigdata-interop#134]
I wanted to setup a dataproc cluster for multi user. Since the compute engine of Dataproc cluster uses a default service or custom service account credentials to connect to storage bucket using `--properties core:fs.gs.auth.service.account.json.keyfile` which doesn't have any relation with user principals who submits the jobs or I couldn't find an option to control it, which makes the dataproc cluster **unsecure** and creates a problem **it introduces another level of indirection in multi-user environment, when key file used does not correspond to principal.**

In my case we are submitting the job using `gcloud dataproc jobs submit hadoop `because my thought is to controls access to dataproc cluster using IAM roles but during the job submission the user principals are not getting forward to the hadoop cluster and as well as `gcloud cli` doesn't perform any access validation on storage buckets at client side , the job always executed as `root` user. May I know how to map the users to their service account do you have any solution for this case?

All we need is the Hadoop Map Reduce submitted by users using `gcloud dataproc jobs submit hadoop ` should be able to use only the storage buckets or folder which user has access to it.

**Current:**
_gcloud dataproc jobs (IAM - user principal)_ **->** _Dataproc Cluster (IAM - user principal)_ **->** _(SA Default/custom)_ **->** _Storage Bucket_

**Required:**
_gcloud dataproc jobs (IAM - user principal)_ **->** _Dataproc Cluster (IAM - user principal)_ **->** _(IAM - user principal)_ **->** _Storage Bucket_

So far I couldn't find a way to do it. Can you please help me on it

Is there any workaround or solution available to this problem?

**Comment by as-sher** [comment]
Hi karth295,

I am facing the same issue, Do you have any updates on the following?

**Comment by locona** [comment]
@krishnabigdata 
I am facing the same issue

How did you solve it?

**Comment by medb** [comment]
@locona, what is your use case and what do you want to achieve? Do you want to use multi-tenant Dataproc cluster for interactive use cases (Jupyter/Zeppelin notebooks) or batch/stream jobs (Spark/Hadoop MR/Flink)?

The more details you will provide the better advice we will be able to give for you.

**Comment by locona** [comment]
@medb 
> Do you want to use multi-tenant Dataproc cluster for interactive use cases (Jupyter/Zeppelin notebooks) or batch/stream jobs (Spark/Hadoop MR/Flink)?

Yes.
I want to  to use multiple service accounts in one spark job in dataproc.
Because the service account is managed by the customer, we can not manage it.

---- 
### The following are the settings and their errors.

**The one task**
```
    spark.sparkContext.hadoopConfiguration.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    spark.sparkContext.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")

    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.email", "first@gmail.com")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key.id", "xxxxxxxxxxxx")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key", "xxxxxxxxxxxx")

    spark.sparkContext.hadoopConfiguration.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    spark.sparkContext.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
```
**Another task**
```
    // set config
    spark.sparkContext.hadoopConfiguration.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
    spark.sparkContext.hadoopConfiguration.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")

    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.email", "second@gmail.com")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key.id", "xxxxxxxxxxxx")
    spark.sparkContext.hadoopConfiguration.set("fs.gs.auth.service.account.private.key", "xxxxxxxxxxxx")
```

**Here is the content of the error.**
```
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "xxxxxxxxx-compute@developer.gserviceaccount.com does not have storage.objects.get access to bucket/hoge/fuga/part-00000-34e1f462-28b9-4095-83f9-ce70eeb19ec8-c000.csv.",
    "reason" : "forbidden"
  } ],
  "message" : "xxxxxxxxx-compute@developer.gserviceaccount.com does not have storage.objects.get access to bucket/hoge/fuga/part-00000-34e1f462-28b9-4095-83f9-ce70eeb19ec8-c000.csv."
}
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:401)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1097)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1939)
	... 45 more
```

**Comment by dennishuo** [comment]
@locona In your case it sounds like you're not asking for secure isolation between the uses of the two different service accounts in the same Dataproc cluster, is that accurate?

In your case the `fs.gs.auth.service.account.private.key` setting is the right track - it should be causing [shouldUseMetadataService](https://github.com/GoogleCloudDataproc/bigdata-interop/blob/master/util/src/main/java/com/google/cloud/hadoop/util/CredentialConfiguration.java#L170) to return `false` due to `serviceAccountPrivateKey` being parsed from that config key.

So your error is more likely due to the spark hadoopConfiguration not being propagated at the right time. Are you setting the two different hadoopConfigurations in the same running driver process?

**Comment by locona** [comment]
@dennishuo  
> In your case it sounds like you're not asking for secure isolation between the uses of the two different service accounts in the same Dataproc cluster, is that accurate?

yes.

> So your error is more likely due to the spark hadoopConfiguration not being propagated at the right time. Are you setting the two different hadoopConfigurations in the same running driver process?

yes. 

My product cannot be isolated because I need to be able to enter a service account arbitrarily for each task.
And they all work with the same driver process.

For example, the first task gets data from GCS of `company-A` of project id , and the second task reads data from GCS of` company-B` of project id and finally writes it to Mysql.

**Comment by dennishuo** [comment]
Thanks for the info! What you're describing should be possible already with some workarounds in your job code, but could potentially also be a feature to add to the GCS connector. It's a bit different from this original feature request since this original feature request was more about having a way to securely isolate different users and processes that share a single cluster.

Are you also running multiple SparkContexts in the same driver, or were you trying to modify the hadoopConfiguration on an existing SparkContext after step A?

If you don't rely on things like `spark.read` or `SparkContext.textFiles` directly, you can always have much finer-grained control of individual FileSystem instances at a per-task granularity. For example, suppose you have:

gs://company-a/data-a/*.txt
gs://company-b/data-b/*.txt

your code can effectively manage those datasets manually like this:

    import org.apache.hadoop.fs.FileSystem;
    import org.apache.hadoop.fs.Path;
    import org.apache.hadoop.conf.Configuration;

    val confA = new Configuration();
    confA.set("fs.gs.auth.service.account.email", "first@gmail.com")
    ...

    val confB = new Configuration();
    confB.set("fs.gs.auth.service.account.email", "second@gmail.com")

    val pathA = new Path("gs://company-a/data-a/")
    val rddA = sc.parallelize(pathA.getFileSystem(confA).listStatus(pathA)).flatMap(filename => {
      val fs = new Path(filename).getFileSystem(confA)
      val dataInput = fs.open(filename)
      val values = new ArrayList
      // manually read all the values from the from dataInput
      return values 
    })

    val pathB = new Path("gs://company-b/data-b/")
    val rddB = sc.parallelize(pathB.getFileSystem(confB).listStatus(pathB)).flatMap(filename => {
      val fs = new Path(filename).getFileSystem(confB)
      val dataInput = fs.open(filename)
      val values = new ArrayList
      // manually read all the values from the from dataInput
      return values 
    })

Based on my limited testing it's a bit tricky to make Spark actually propagate hadoop configuration changes to the workers properly if resetting them at runtime.

**Comment by locona** [comment]
@dennishuo 

> Are you also running multiple SparkContexts in the same driver, or were you trying to modify the hadoopConfiguration on an existing SparkContext after step A?

the latter.
The following is an image diagram.
Pipeline is created by one spark application.

![image](https://user-images.githubusercontent.com/18649881/77643684-26d3f980-6fa3-11ea-8b35-f062b3f61cae.png)

Because it is related to spark-bigquery-connector,
Our method did not solve our problem.

https://github.com/GoogleCloudDataproc/spark-bigquery-connector
