### ISSUE TITLE
Unreasonably slow write to BigQuery

### ISSUE THREAD

**Issue by omarzouk** [GoogleCloudPlatform/bigdata-interop#157]
Hi,

I'm running a big computation job on Dataproc to do audio processing and write to BQ. The job finishes the audio processing in roughly 10 hours. However, the job has been stuck trying to write to BigQuery for more than 10 hours.

There were no errors or failures for any tasks or stages. When I look at the logs of the tasks that are still running, this is what I see:

```
19/03/24 02:41:04 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from default credential.
19/03/24 02:41:04 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from given credential.
19/03/24 02:41:04 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputFormat: Delegating functionality to 'TextOutputFormat'.
19/03/24 02:42:12 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputFormat: Delegating functionality to 'TextOutputFormat'.
19/03/24 02:42:12 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from default credential.
19/03/24 02:42:12 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from given credential.
19/03/24 02:42:12 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputFormat: Delegating functionality to 'TextOutputFormat'.
19/03/24 02:42:36 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputFormat: Delegating functionality to 'TextOutputFormat'.
19/03/24 02:42:36 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from default credential.
19/03/24 02:42:36 INFO com.google.cloud.hadoop.io.bigquery.BigQueryFactory: Creating BigQuery from given credential.
19/03/24 02:42:36 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputFormat: Delegating functionality to 'TextOutputFormat'.
```

Note the timestamp, 02:42 am, this was 10 hours ago, the task is still running right now trying to write to BigQuery.

The output size is ~15 GB, roughly 40 million records. The same amount of data takes 10 minutes to write when using DataFlow. I know this because this pipeline used to be Dataflow, but we decided to move it to Dataproc for cost savings.

I'm not using any preemtible instances in the cluster.

**Comment by medb** [comment]
May you capture stack traces of the job with `jstack` when it hangs?

Maybe this is related to the #153

**Comment by medb** [comment]
Actually, if it works fast on Dataflow, it's most probably not related to #153.

It still will be good to see stack traces to understand what part of the pipeline is slow.

**Comment by omarzouk** [comment]
I will try to get the stack trace in the future. The job successfully ended after running for 24 hours, after I added an auto-scaling policy to the cluster since the majority of the workers were idle and it was an unnecessary cost, not sure if the killing of the workers triggered a data shuffle, but the write was then successful and this is the output:

Got a few errors like this one (since machines were killed):
```
org.apache.spark.scheduler.TaskSetManager: Lost task 13.0 in stage 1.1
org.apache.spark.shuffle.FetchFailedException: Failed to connect to XXXXX
```

Then spark retried some tasks:
```
[Stage 0:>                                                        (0 + 20) / 20]
[Stage 0:==>                                                      (1 + 19) / 20]
[Stage 0:=====>                                                   (2 + 18) / 20]
[Stage 0:========>                                                (3 + 17) / 20]
[Stage 0:===========>                                             (4 + 16) / 20]
[Stage 0:=================>                                       (6 + 14) / 20]
[Stage 0:===================>                                     (7 + 13) / 20]
[Stage 0:======================>                                  (8 + 12) / 20]
```

then the tasks that were hanging (25 out of 10k) got unblocked for some reason:

```
19/03/24 13:22:07 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
[Stage 1:=============================>                          (13 + 12) / 25]
[Stage 1:=============================>                          (13 + 12) / 25]
[Stage 1:===============================>                        (14 + 11) / 25]
[Stage 1:=================================>                      (15 + 10) / 25]
[Stage 1:====================================>                    (16 + 9) / 25]
[Stage 1:======================================>                  (17 + 8) / 25]19/03/24 13:25:48 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:25:48 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
[Stage 1:=========================================>               (18 + 7) / 25]
[Stage 1:===========================================>             (19 + 6) / 25]19/03/24 13:26:51 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:26:51 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
[Stage 1:===========================================>             (19 + 6) / 25]19/03/24 13:27:18 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:27:18 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
[Stage 1:=============================================>           (20 + 5) / 25]
[Stage 1:===============================================>         (21 + 4) / 25]
[Stage 1:==================================================>      (22 + 3) / 25]
[Stage 1:====================================================>    (23 + 2) / 25]
[Stage 1:======================================================>  (24 + 1) / 25]19/03/24 13:29:46 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:29:46 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:29:58 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:29:58 WARN org.apache.spark.ExecutorAllocationManager: No stages are running, but numRunningTasks != 0
                                                                                
19/03/24 13:29:58 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:30:02 INFO com.google.cloud.hadoop.io.bigquery.BigQueryHelper: Importing into table 'XXXXXXXXXXX:XXXXXXXXX' from 10000 paths; path[0] is 'gs://XXXXXXXXXXX-tmp/cl/324372/part-r-00000'; awaitCompletion: true
19/03/24 13:30:02 INFO com.google.cloud.hadoop.io.bigquery.BigQueryHelper: Using provided import schema '{fields=[{"mode":"NULLABLE","name":"url","type":"STRING"}, {"mode":"NULLABLE","name":"entityType","type":"STRING"}, {"mode":"NULLABLE","name":"providerName","type":"STRING"}, {"mode":"NULLABLE","name":"providerVersion","type":"STRING"}, {"mode":"NULLABLE","name":"originId","type":"STRING"}, {"mode":"NULLABLE","name":"essentiaJson","type":"STRING"}]}'.
19/03/24 13:30:31 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:30:31 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:38:26 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputCommitter: Found GCS output data at 'gs://XXXXXXXXXXX-tmp/cl/324372', attempting to clean up.
19/03/24 13:38:33 INFO com.google.cloud.hadoop.io.bigquery.output.ForwardingBigQueryFileOutputCommitter: Successfully deleted GCS output path 'gs://XXXXXXXXXXX-tmp/cl/324372'.
19/03/24 13:38:34 ERROR org.apache.spark.scheduler.LiveListenerBus: Listener EventLoggingListener threw an exception
java.io.IOException: All datanodes [DatanodeInfoWithStorage[10.128.0.106:9866,DS-5283ffdf-fa20-4b03-a0cf-517acb27a93a,DISK]] are bad. Aborting...
	at org.apache.hadoop.hdfs.DataStreamer.handleBadDatanode(DataStreamer.java:1531)
	at org.apache.hadoop.hdfs.DataStreamer.setupPipelineForAppendOrRecovery(DataStreamer.java:1465)
	at org.apache.hadoop.hdfs.DataStreamer.processDatanodeError(DataStreamer.java:1237)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:657)
19/03/24 13:38:34 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@763cf5b9{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
Job output is complete
```

I have hidden the project name, bigquery table name and cluster name from the logs

Hope this helps, let me know if you would like access to the full output, I can send it to you via email.

**Comment by medb** [comment]
May you provide small repro so we will be able to debug it on our end as well?
