### ISSUE TITLE
bigquery connector no such field error is not useful.

### ISSUE THREAD

**Issue by christian-lefty** [GoogleCloudPlatform/bigdata-interop#22]
can the error message include the name of the field pretty please.
```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.io.IOException: no such field
    at com.google.cloud.hadoop.io.bigquery.BigQueryUtils.waitForJobCompletion(BigQueryUtils.java:97)
    at com.google.cloud.hadoop.io.bigquery.BigQueryRecordWriter$BigQueryAsyncWriteChannel.handleResponse(BigQueryRecordWriter.java:135)
    at com.google.cloud.hadoop.io.bigquery.BigQueryRecordWriter$BigQueryAsyncWriteChannel.handleResponse(BigQueryRecordWriter.java:100)
    at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel.close(AbstractGoogleAsyncWriteChannel.java:289)
    at com.google.cloud.hadoop.io.bigquery.BigQueryRecordWriter.close(BigQueryRecordWriter.java:360)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$5.apply$mcV$sp(PairRDDFunctions.scala:1043)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1215)
```

**Comment by criccomini** [comment]
+1 this error message is pretty hard to work with

**Comment by p1mps** [comment]
+1
