### ISSUE TITLE
Crashes / failures on key paths with odd characters in them

### ISSUE THREAD

**Issue by freben** [GoogleCloudPlatform/bigdata-interop#27]
I have a test bucket with the following first level key path components:

![screen shot 2016-02-16 at 11 18 06](https://cloud.githubusercontent.com/assets/3097461/13073727/910a4932-d4a0-11e5-8f45-0fdd8e9078d4.png)

Attempting to list that directory via the connector gives the following:

```$ hadoop fs -ls 'gs://<redacted>'
16/02/16 10:18:36 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.0-hadoop2
16/02/16 10:18:40 ERROR gcsio.GoogleCloudStorageFileSystem: Invalid bucket name (<redacted>) or object name (a b/)
java.net.URISyntaxException: Illegal character in path at index 20: gs://<redacted>/a b/
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getPath(GoogleCloudStorageFileSystem.java:1566)
	at com.google.cloud.hadoop.gcsio.FileInfo.<init>(FileInfo.java:70)
	at com.google.cloud.hadoop.gcsio.FileInfo.fromItemInfo(FileInfo.java:252)
	at com.google.cloud.hadoop.gcsio.FileInfo.fromItemInfos(FileInfo.java:263)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:995)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:1050)
	at org.apache.hadoop.fs.shell.PathData.getDirectoryContents(PathData.java:268)
	at org.apache.hadoop.fs.shell.Command.recursePath(Command.java:347)
	at org.apache.hadoop.fs.shell.Ls.processPathArgument(Ls.java:90)
	at org.apache.hadoop.fs.shell.Command.processArgument(Command.java:260)
	at org.apache.hadoop.fs.shell.Command.processArguments(Command.java:244)
	at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:190)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:154)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)
-ls: Invalid bucket name (<redacted>) or object name (a b/)
Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]```

The following works:

```hadoop fs -ls 'gs://<redacted>/a%20b'```

The following does not:

```hadoop fs -ls 'gs://<redacted>/a b'```
```hadoop fs -ls 'gs://<redacted>/a?b'```
```hadoop fs -ls 'gs://<redacted>/a#b'```
```hadoop fs -ls 'gs://<redacted>/a%23b'```
```hadoop fs -ls 'gs://<redacted>/a%3Fb'```
```hadoop fs -ls 'gs://<redacted>/a%2523b'```
```hadoop fs -ls 'gs://<redacted>/a%253Fb'```

**Comment by AngusDavis** [comment]
Hi @freben, thanks for reporting this. We're currently working on getting round tripping working decently with the intermediate URI representation used in GoogleCloudStorageFileSystem. I'll update this issue when we have something.

**Comment by AngusDavis** [comment]
It took a little longer to to get this pushed than I was hoping. Connector version 1.4.5 / commit acf5cf08e9547c39fd4ed3cb01a7ec3c41087a5d adds a new configuration option to opt-in to new path handling. It *should* be fully compatibile with the old path handling, but it was added opt-in for a release just to be safe. 

To opt-in, set the Hadoop configuration key 'fs.gs.path.encoding' to 'uri-path'.
