### ISSUE TITLE
Space not allowed in file name

### ISSUE THREAD

**Issue by achyan** [GoogleCloudPlatform/bigdata-interop#31]
I have existing code that creates files with spaces in the name. It works in HDFS, and it also works when creating the file using gsutil, but it fails when using gcs-connector.

$ gsutil cp /tmp/cloud-dmp/.metadata_never_index "gs://cloud-dmp/a b c"
Copying file:///tmp/cloud-dmp/.metadata_never_index [Content-Type=application/octet-stream]...

$ hadoop fs -mkdir "gs://cloud-dmp/tmp/a b"
16/04/08 12:08:00 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.2-hadoop2
16/04/08 12:08:01 ERROR gcsio.GoogleCloudStorageFileSystem: Invalid bucket name (cloud-dmp) or object name (tmp/a b)
java.net.URISyntaxException: Illegal character in path at index 20: gs://cloud-dmp/tmp/a b
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getPath(GoogleCloudStorageFileSystem.java:1567)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem.getGcsPath(GoogleHadoopFileSystem.java:173)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:1167)
	at org.apache.hadoop.fs.FileSystem.globStatusInternal(FileSystem.java:1683)
	at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1629)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1338)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.globStatus(GoogleHadoopFileSystemBase.java:1261)

**Comment by AngusDavis** [comment]
HI @achyan - could you upgrade to the latest version of the connector (1.4.5) if you are not already on it and try applying the settings outlined in the CHANGES.txt to enable new path encoding (set 'fs.gs.path.encoding' to 'uri-path')?

**Comment by AngusDavis** [comment]
Sorry, meant to link to CHANGES.txt. It can be found here: https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/CHANGES.txt#L3

**Comment by achyan** [comment]
Ah, yes. Now I'm able to run: hadoop fs -mkdir "gs://cloud-dmp/tmp/a b". I'll close this issue. Thanks.
