### ISSUE TITLE
LeaseExpiredException when copying many files from gcs to HDFS

### ISSUE THREAD

**Issue by jburos** [GoogleCloudPlatform/bigdata-interop#60]
Hi,

We're syncing large numbers of files from a google bucket to HDFS using the gcs_connector. This works great, up to a point -- maybe 100 files in? -- after which point we start seeing a number of `LeaseExpiredException`s. 

Specifically:

``` 
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /datasets/path/to/destination/directory/on/hdfs/union-effects.pkl._COPYING_ (inode 36373244): File does not exist. Holder DFSClient_NONMAPREDUCE_-1721918755_1 does not have any open files.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3602)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.analyzeFileState(FSNamesystem.java:3399)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3255)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:676)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:212)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:483)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
```

Typically, once we see these they proceed for the subsequent files being downloaded. If we kill the processes & start again, the download for the files succeeds until a number of files have downloaded, at which point it starts up again. 

For the sake of completeness, we are using the following bash snippet to download the files:

```sh
#!/usr/bin/env bash

if [ $# -ne 2 ]; then
        echo "Usage: $0 <src> <dest>" >&2
        exit 1
fi

export SRC="$1"
shift
export DEST="$1"
shift

echo "Copying from $SRC to $DEST"

export hl="hdfs dfs $hadoop_args -Dfs.gs.path.encoding=uri-path -ls"
export hc="hdfs dfs $hadoop_args -Dfs.gs.path.encoding=uri-path -cp"
export ht="hdfs dfs $hadoop_args -Dfs.gs.path.encoding=uri-path -test"
export gsl="gsutil ls"

one_file() {
        file="$1"
        if ! $ht -e "$DEST/$file" 2> /dev/null; then
                echo -n "Copying: $SRC/$file to $DEST/$file"
                err="$(mktemp)"
                if $hc "$SRC/$file" "$DEST/$file" 2>"$err"; then
                        echo " done"
                else
                        echo " error!"
                        cat "$err"
                fi
                rm -f "$err"
        else
                echo "Found: $DEST/$file"
        fi
}

export -f one_file

$hl -R $SRC 2>/dev/null \
| tail -n +2 \
| sed "s_^.* ${SRC}/__" \
| parallel -j+0 --env hc,ht,SRC,DEST,one_file 'one_file'
```

Wondering (hoping) you might have some insight as to what might be causing these errors?

This ends up being about 24 processes running in parallel.

(addendum):
Here is another, possibly more complete log of this error:

```
Copying: gs://bucket-name/rna/etc-etc-etc-read-name-sorted.bam to /datasets/bucket-name/rna/etc-etc-etc-read-name-sorted.bam error!
17/07/27 19:53:43 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.1-hadoop2
17/07/27 19:53:44 WARN gcs.GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://bucket-name/'
17/07/27 19:53:45 WARN hdfs.DFSClient: DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /datasets/bucket-name/rna/etc-etc-etc-read-name-sorted.bam._COPYING_ (inode 36384065): File does not exist. Holder DFSClient_NONMAPRED
UCE_-1837747866_1 does not have any open files.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:3602)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.analyzeFileState(FSNamesystem.java:3399)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3255)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:676)
        at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:212)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:483)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2086)
        at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2082)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2080)

        at org.apache.hadoop.ipc.Client.call(Client.java:1472)
        at org.apache.hadoop.ipc.Client.call(Client.java:1403)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
        at com.sun.proxy.$Proxy14.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:399)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:252)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
        at com.sun.proxy.$Proxy15.addBlock(Unknown Source)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1674)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1471)
        at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:668)
17/07/27 19:53:45 WARN gcsio.GoogleCloudStorageReadChannel: Channel for 'gs://bucket-name/rna/etc-etc-etc-read-name-sorted.bam' is not open.
cp: No lease on /datasets/bucket-name/rna/etc-etc-etc-read-name-sorted.bam._COPYING_ (inode 36384065): File does not exist. Holder DFSClient_NONMAPREDUCE_-1837747866_1 does not have any open files.
 ```

**Comment by jburos** [comment]
Think we figured this out, -- don't think it involves the gc_connector -- but posting here in case someone else encounters this. 

Current theory is that two nodes are trying to write to the same file, and when one completes it deletes the `._COPYING_` file, causing an error on the other (or some variation of this is occurring during copying before completion).

The file listing by which we are copying includes directories, so if I run in one process (`-j1`) to download files to _an empty directory_ i see the following:
```
Copying: gs://bucket-name/for-msk-bms-lung/downloads/0017a332-c7fd-41ca-8cb9-cd8d81f1cb24 to /datasets/bucket-name/for-msk-bms-lung/downloads/0017a332-c7fd-41ca-8cb9-cd8d81f1cb24 done
Found: /datasets/bucket-name/for-msk-bms-lung/downloads/0017a332-c7fd-41ca-8cb9-cd8d81f1cb24/C508.TCGA-60-2721-11A-01D-1522-08.5_gdc_realn.bai
Found: /datasets/bucket-name/for-msk-bms-lung/downloads/0017a332-c7fd-41ca-8cb9-cd8d81f1cb24/C508.TCGA-60-2721-11A-01D-1522-08.5_gdc_realn.bam
# ...
```

So it’s copying the directory, then each file or directory within the directory. When this gets parallelized, the files within the directories are then trying to be “copied” by more than one process simultaneously. This gets really messy, particularly when we have several nested directories. The same file might be being copied by several processes at once, and so it's only a matter of time until there's a collision.

After modifying the script to exclude directories, and instead do a `-mkdir -p` on the dirname for each file listed, we haven't seen any problems yet. Will come back to close this once it's error-free for some time.
