### ISSUE TITLE
[Kind/Help] Exception in thread "main" java.lang.NoSuchFieldError: GCS_SCOPES

### ISSUE THREAD

**Issue by akhilputhiry** [GoogleCloudPlatform/bigdata-interop#73]
I am trying to read and write into big query from hadoop/spark using this [example](https://cloud.google.com/dataproc/docs/tutorials/bigquery-connector-spark-example). I have configured the gcs connector as mentioned [here](https://cloud.google.com/dataproc/docs/concepts/connectors/install-storage-connector). When I try to list the data using `hadoop fs -ls gs://big_query_test` I am getting the following error. can someone help me to understand this.

```
akhilputhiry@akhilputhiry-Latitude-3450:~/opt/hadoop/etc/hadoop$ hadoop fs -ls gs://big_query_test
17/11/01 18:04:08 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.1-hadoop2
Exception in thread "main" java.lang.NoSuchFieldError: GCS_SCOPES
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1824)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1012)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:975)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2812)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2849)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2831)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
	at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:245)
	at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:228)
	at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:103)
	at org.apache.hadoop.fs.shell.Command.run(Command.java:175)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:315)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:378)
```

**Comment by pcejrowski** [comment]
I face the same problems running Scala from Toree kernels in Jupyter.
This field comes from `com.google.cloud.hadoop.util.CredentialFactory`.
Using the same kernel I can do: 
```scala
println(com.google.cloud.hadoop.util.CredentialFactory.GCS_SCOPES)
```
and it prints the right value:
```
[https://www.googleapis.com/auth/devstorage.full_control]
```

**Comment by medb** [comment]
Most probably this is happening because you have multiple GCS connectors jars on classpath.

Usually you should specify GCS connector dependency as "provided" in your application if it already deployed to the cluster (as in case with Datproc) to avoid this.

Closing, until further information will be provided.
