### ISSUE TITLE
AppEngine exported logs requires Writer permissions for reading

### ISSUE THREAD

**Issue by motymichaely** [GoogleCloudPlatform/bigdata-interop#9]
When using the [GoogleHadoopFileSystem](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/src/main/java/com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystemBase.java) to __read__ [AppEngine logs](https://cloud.google.com/logging/docs/export/configure_export) exported to Google Cloud Storage, an `Access Denied` exception is thrown when using a user that has only read permissions to the bucket and key of the exported logs.

**Comment by AngusDavis** [comment]
Which version of the connector are you using?

**Comment by motymichaely** [comment]
@AngusDavis - 1.2.9

**Comment by motymichaely** [comment]
I've also tried with 1.4.1:

```
$ hadoop fs -lsr gs://xplenty-tests/appengine.googleapis.com/request_log/2015

15/07/21 11:56:29 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.1-hadoop1
15/07/21 11:56:30 WARN gcs.GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://xplenty-tests/'
drwx------   - root root          0 2015-07-16 13:44 /appengine.googleapis.com/request_log/2015
drwx------   - root root          0 2015-07-16 13:44 /appengine.googleapis.com/request_log/2015/07
15/07/21 11:56:31 WARN gcsio.GoogleCloudStorage: Repairing batch of 1 missing directories.
15/07/21 11:56:31 ERROR gcsio.GoogleCloudStorage: Failed to repair some missing directories.
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Forbidden",
    "reason" : "forbidden"
  } ],
  "message" : "Forbidden"
  }
at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.createEmptyObject(GoogleCloudStorageImpl.java:433)
at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.createEmptyObject(GoogleCloudStorageImpl.java:446)
at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.listObjectInfo(GoogleCloudStorageImpl.java:1204)
at com.google.cloud.hadoop.gcsio.CacheSupplementedGoogleCloudStorage.listObjectInfo(CacheSupplementedGoogleCloudStorage.java:471)
at com.google.cloud.hadoop.gcsio.CacheSupplementedGoogleCloudStorage.listObjectInfo(CacheSupplementedGoogleCloudStorage.java:453)
at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:991)
at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:1050)
at org.apache.hadoop.fs.FsShell.shellListStatus(FsShell.java:1303)
at org.apache.hadoop.fs.FsShell.ls(FsShell.java:604)
at org.apache.hadoop.fs.FsShell.ls(FsShell.java:647)
at org.apache.hadoop.fs.FsShell.ls(FsShell.java:647)
at org.apache.hadoop.fs.FsShell.ls(FsShell.java:593)
at org.apache.hadoop.fs.FsShell.doall(FsShell.java:1734)
at org.apache.hadoop.fs.FsShell.run(FsShell.java:1984)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
at org.apache.hadoop.fs.FsShell.main(FsShell.java:2090)
```

**Comment by dennishuo** [comment]
Can you try with 1.4.1 and setting "fs.gs.implicit.dir.repair.enable" to "false" in your config? The "write" should only be due to the attempt to repair a missing directory object, but aside from worse performance in listing directory stats, it's fine to just turn off the directory-repair feature when using the connector for read-only mode.

**Comment by motymichaely** [comment]
@dennishuo - I've tried both 1.4.1 and setting "fs.gs.implicit.dir.repair.enable" to "false" with no luck:

```
hadoop fs -Dfs.gs.implicit.dir.repair.enable=false -lsr gs://xplenty-tests/appengine.googleapis.com/request_log/2015/
```

```
15/08/25 07:32:41 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.1-hadoop1
15/08/25 07:32:41 WARN gcs.GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://xplenty-tests/'
drwx------   - root root          0 2015-07-16 13:44 /appengine.googleapis.com/request_log/2015/07
15/08/25 07:32:45 ERROR gcsio.GoogleCloudStorage: Error retrieving object for a retrieved prefix with resourceId 'gs://xplenty-tests/appengine.googleapis.com/request_log/2015/07/21/'. Giving up on retrieving missing directory.
drwx------   - root root          0 2015-07-16 13:44 /appengine.googleapis.com/request_log/2015/07/16
-rwx------   3 root root      83153 2015-07-16 13:26 /appengine.googleapis.com/request_log/2015/07/16/12:00:00_12:59:59_S0.json
-rwx------   3 root root       8607 2015-07-16 14:24 /appengine.googleapis.com/request_log/2015/07/16/13:00:00_13:59:59_S0.json
```

I've managed to work it around is using globbing pattern but again, with some exceptions:

```
hadoop fs -lsr gs://xplenty-tests/appengine.googleapis.com/request_log/2015/*
```

```
15/08/25 07:33:38 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.4.1-hadoop1
15/08/25 07:33:38 WARN gcs.GoogleHadoopFileSystemBase: No working directory configured, using default: 'gs://xplenty-tests/'
15/08/25 07:33:40 WARN gcsio.GoogleCloudStorage: Repairing batch of 1 missing directories.
15/08/25 07:33:40 ERROR gcsio.GoogleCloudStorage: Failed to repair some missing directories.
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Forbidden",
    "reason" : "forbidden"
  } ],
  "message" : "Forbidden"
}
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Forbidden",
    "reason" : "forbidden"
  } ],
  "message" : "Forbidden"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:423)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.createEmptyObject(GoogleCloudStorageImpl.java:335)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.createEmptyObject(GoogleCloudStorageImpl.java:348)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.listObjectInfo(GoogleCloudStorageImpl.java:949)
	at com.google.cloud.hadoop.gcsio.CacheSupplementedGoogleCloudStorage.listObjectInfo(CacheSupplementedGoogleCloudStorage.java:455)
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.listFileInfo(GoogleCloudStorageFileSystem.java:927)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.listStatus(GoogleHadoopFileSystemBase.java:823)
	at org.apache.hadoop.fs.FsShell.shellListStatus(FsShell.java:1303)
	at org.apache.hadoop.fs.FsShell.ls(FsShell.java:604)
	at org.apache.hadoop.fs.FsShell.ls(FsShell.java:593)
	at org.apache.hadoop.fs.FsShell.doall(FsShell.java:1734)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:1984)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:2090)

drwx------   - root root          0 2015-07-16 13:44 /appengine.googleapis.com/request_log/2015/07/16
-rwx------   3 root root      83153 2015-07-16 13:26 /appengine.googleapis.com/request_log/2015/07/16/12:00:00_12:59:59_S0.json
-rwx------   3 root root       8607 2015-07-16 14:24 /appengine.googleapis.com/request_log/2015/07/16/13:00:00_13:59:59_S0.json
```
But this call also tried to repair some missing implicit directories. So none of the above solutions is a good fit.

**Comment by motymichaely** [comment]
@dennishuo - My bad, seems like the jar wasn't the correct one. 
Now it works when setting "fs.gs.implicit.dir.repair.enable" to "false".

Would you please mind elaborating more on performance impact?

**Comment by dennishuo** [comment]
The performance impact is only on "metadata operations", for example during initial listing for job setup, so it shouldn't really be noticeable since the main part of any jobs won't hit the extra metadata-listing path. Essentially during setup, when trying to stat a parent directory before listing inside it, the code must perform an extra round-trip which first fails to retrieve the "placeholder directory object" and then issues a prefix-listing to look for "implicit directories", which would take anywhere from maybe 100ms to 500ms. A few percent of the time it might take up to an extra 1 second.

But that should only be during job setup, so not noticeable in general.

**Comment by motymichaely** [comment]
@dennishuo - Thanks! 

I'll keep posted here if we see dramatic performance hit due to this setting.

**Comment by aditpshrimal** [comment]
I am facing the same issue. I am submitting spark job using console. How do I set the config?_

**Comment by medb** [comment]
> I am facing the same issue. I am submitting spark job using console. How do I set the config?

Going forward, please, create a new issue with detailed explanation of the problem that you are facing, instead of posting on the 5-years old closed issue.

On how to set Dataproc properties refer to [the documentation](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties#console).

All GCS connector properties are lister [here](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md).
